INSTALL PLUGIN js_daemon SONAME 'mysqlv8udfs.so';

CREATE FUNCTION js RETURNS STRING SONAME 'mysqlv8udfs.so';
CREATE FUNCTION jsudf RETURNS STRING SONAME 'mysqlv8udfs.so';
CREATE AGGREGATE FUNCTION jsagg RETURNS STRING SONAME 'mysqlv8udfs.so';
